### ISSUE TITLE
Poder guardar como json_pretty: true la respuesta obtenida de un plugin

### ISSUE THREAD

**Issue by juanmiguelguerrero** [e-xisto/base-fetchql#6]
En la mayoría de los casos debemos ver la estructura del JSON que generamos con nuestros plugins.

Necesitamos poder configurar el parámetro `json_pretty: true` en la configuración del plugin para que el JSON se guarde bonito.

**Comment by CesarEGarcia** [comment]
Esa propiedad ya existe y debe de funcionar


type PluginQLData = {
	function: Function;
	data: Array <string>;
	output?: string;
	json_pretty?: boolean;
}
